<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="1" total="8" passed="6">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="65" started-at="2022-03-03T13:12:48Z" finished-at="2022-03-03T13:12:48Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="65" started-at="2022-03-03T13:12:48Z" finished-at="2022-03-03T13:12:48Z">
      <class name="org.assertsoftn.A">
        <test-method status="FAIL" signature="testA1()[pri:0, instance:org.assertsoftn.A@6e0dec4a]" name="testA1" duration-ms="10" started-at="2022-03-03T13:12:48Z" finished-at="2022-03-03T13:12:48Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at org.assertsoftn.A.testA1(A.java:9)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA1 -->
        <test-method status="PASS" signature="testA2()[pri:0, instance:org.assertsoftn.A@6e0dec4a]" name="testA2" duration-ms="1" started-at="2022-03-03T13:12:48Z" finished-at="2022-03-03T13:12:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA2 -->
        <test-method status="PASS" signature="testA3()[pri:0, instance:org.assertsoftn.A@6e0dec4a]" name="testA3" duration-ms="1" started-at="2022-03-03T13:12:48Z" finished-at="2022-03-03T13:12:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testA3 -->
      </class> <!-- org.assertsoftn.A -->
      <class name="org.assertsoftn.B">
        <test-method status="PASS" signature="testB2()[pri:0, instance:org.assertsoftn.B@96def03]" name="testB2" duration-ms="2" started-at="2022-03-03T13:12:48Z" finished-at="2022-03-03T13:12:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB2 -->
        <test-method status="PASS" signature="testB3()[pri:0, instance:org.assertsoftn.B@96def03]" name="testB3" duration-ms="1" started-at="2022-03-03T13:12:48Z" finished-at="2022-03-03T13:12:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testB3 -->
      </class> <!-- org.assertsoftn.B -->
      <class name="org.assertsoftn.C">
        <test-method status="PASS" signature="testC2()[pri:0, instance:org.assertsoftn.C@5ccddd20]" name="testC2" duration-ms="1" started-at="2022-03-03T13:12:48Z" finished-at="2022-03-03T13:12:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testC2 -->
        <test-method status="PASS" signature="testC3()[pri:0, instance:org.assertsoftn.C@5ccddd20]" name="testC3" duration-ms="3" started-at="2022-03-03T13:12:48Z" finished-at="2022-03-03T13:12:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testC3 -->
      </class> <!-- org.assertsoftn.C -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
